#!/usr/bin/env python3
"""
BioTransformer Pipeline
=======================
Predicts microbial metabolic transformation products for annotated LC-MS/MS
features, running BioTransformer 3.0 in parallel across all compounds.

This script is Step 1 of a two-step annotation loop:

  Step 1 (this script):
    - Input:  data/biotransformer/{batch}_compounds_for_biotransformer.csv
              (generated by Section 3 of process_data_cassava/cocoyam.ipynb)
    - Runs BioTransformer with two biotransformation models:
        env   = environmental/microbial fermentation metabolism
        hgut  = human gut microbial metabolism
    - Output: results/biotransformer/{batch}/
                biotransformer_3step_predictions.csv  (all predicted metabolites)
                individual_results/                   (per-compound CSVs)

  Step 2 (manual, external):
    - Load the predicted SMILES from the output CSV into SIRIUS as a custom
      structure database (Compound.csv format).
    - Re-run SIRIUS/CSI:FingerID with the custom database included.
    - Place the new SIRIUS outputs in data/processed_data/{batch}_biot/.
    - Re-run process_data_cassava/cocoyam.ipynb to produce updated annotations.
    - Features matched uniquely to BioTransformer-predicted structures will appear with
      names prefixed BT_env_step* or BT_hgut_step* in the sirius_links column.

Requirements:
  - Java (for BioTransformer jar)
  - BioTransformer 3.0 jar: https://bitbucket.org/wishartlab/biotransformer3.0jar
  - Pass --bt-dir to point to the directory containing the jar file.

Usage:
  python scripts/biotransformer_sirius.py --batch b3_cassavaonly --bt-dir /path/to/biotransformer
  python scripts/biotransformer_sirius.py --batch b3_cocoyamonly --bt-dir /path/to/biotransformer
"""

import subprocess
import os
import argparse
import pandas as pd
import time
import concurrent.futures
import multiprocessing

# ============================================================================
# CONFIGURATION  (overridable via CLI arguments)
# ============================================================================
DEFAULT_BATCH_ID = "b3_cassavaonly"

# Resolved at runtime via --bt-dir argument; no hardcoded paths.
JAR_FILENAME = "BioTransformer3.0_20230525.jar"

MAX_WORKERS = max(1, multiprocessing.cpu_count() - 1)

# Pipeline settings
BT_TYPES = ["env", "hgut"]
NUM_STEPS = 3


# ============================================================================
# HELPER FUNCTION TO INFER TRANSFORMATION STEPS
# ============================================================================
def infer_transformation_steps(df, origin_smiles):
    """
    Infers the transformation step/generation for each metabolite based on
    the precursor chain. Since BioTransformer doesn't output this directly,
    we reconstruct it.

    Step 1: Precursor is the parent compound
    Step 2: Precursor is a step 1 metabolite
    Step 3: Precursor is a step 2 metabolite
    etc.
    """
    if len(df) == 0:
        return []

    # Map each metabolite SMILES to its assigned step
    step_map = {origin_smiles: 0}  # Origin is step 0

    # Iteratively assign steps
    max_iterations = 15
    for iteration in range(max_iterations):
        assignments_made = 0

        for idx, row in df.iterrows():
            met_smiles = row["SMILES"]
            prec_smiles = row["Precursor SMILES"]

            # Skip if already assigned
            if met_smiles in step_map:
                continue

            # Check if precursor has been assigned a step
            if prec_smiles in step_map:
                step_map[met_smiles] = step_map[prec_smiles] + 1
                assignments_made += 1

        # Stop if no new assignments
        if assignments_made == 0:
            break

    # Build the result list
    steps = []
    for idx, row in df.iterrows():
        met_smiles = row["SMILES"]
        step = step_map.get(met_smiles, 0)
        if step > 0:
            steps.append(step)
        else:
            steps.append(0)  # Unknown

    return steps


# ============================================================================
# WORKER FUNCTION
# ============================================================================
def process_single_task(task_args):
    """
    Runs BioTransformer once for a compound and biotransformation type.
    """
    (row_data, bt_type, output_dir_ind, bt_dir, jar_file) = task_args

    # Unpack row data
    feature_id = row_data["mappingFeatureId"]
    smiles = row_data["smiles"]
    smiles_source = row_data["annotation_source"]
    compound_name = row_data.get("compound_name", "Unknown")
    if pd.isna(compound_name):
        compound_name = "Unknown"

    # Define filenames
    output_filename = f"feature{feature_id}_{bt_type}_step{NUM_STEPS}.csv"
    bt_output_path = os.path.join(bt_dir, output_filename)
    final_output_path = os.path.join(output_dir_ind, output_filename)

    # Cleanup previous run
    if os.path.exists(bt_output_path):
        os.remove(bt_output_path)

    # Build Command
    cmd = [
        "java",
        "-jar",
        jar_file,
        "-k",
        "pred",
        "-b",
        bt_type,
        "-ismi",
        smiles,
        "-ocsv",
        output_filename,
        "-s",
        str(NUM_STEPS),
    ]

    run_start = time.time()
    result_data = None
    status = "error"
    run_time = 0

    try:
        # Run Java Process
        proc = subprocess.run(
            cmd, cwd=bt_dir, capture_output=True, text=True, timeout=300
        )

        run_time = time.time() - run_start

        if os.path.exists(bt_output_path):
            df = pd.read_csv(bt_output_path)
            n_metabolites = len(df)

            if n_metabolites > 0:
                # Add metadata columns
                df["origin_feature"] = feature_id
                df["origin_smiles"] = smiles
                df["origin_name"] = compound_name
                df["smiles_source"] = smiles_source
                df["bt_type"] = bt_type

                # INFER transformation steps from precursor relationships
                transformation_steps = infer_transformation_steps(df, smiles)
                df["transformation_step"] = transformation_steps

                # Reorder columns
                priority_cols = [
                    "origin_feature",
                    "origin_smiles",
                    "origin_name",
                    "smiles_source",
                    "bt_type",
                    "transformation_step",
                ]
                other_cols = [c for c in df.columns if c not in priority_cols]
                df = df[priority_cols + other_cols]

                # Save to final destination
                df.to_csv(final_output_path, index=False)
                result_data = df
                status = "success"
            else:
                status = "no_metabolites"

            # Clean up temp file
            os.remove(bt_output_path)
        else:
            status = "no_output"

    except subprocess.TimeoutExpired:
        run_time = time.time() - run_start
        status = "timeout"
    except Exception as e:
        run_time = time.time() - run_start
        status = f"error: {str(e)[:50]}"

    # Calculate step breakdown
    n_step1 = n_step2 = n_step3 = n_unknown = 0
    if result_data is not None:
        n_step1 = len(result_data[result_data["transformation_step"] == 1])
        n_step2 = len(result_data[result_data["transformation_step"] == 2])
        n_step3 = len(result_data[result_data["transformation_step"] == 3])
        n_unknown = len(result_data[result_data["transformation_step"] == 0])

    # Return summary
    summary = {
        "feature": feature_id,
        "smiles": smiles,
        "compound_name": compound_name,
        "smiles_source": smiles_source,
        "bt_type": bt_type,
        "n_metabolites": len(result_data) if result_data is not None else 0,
        "n_step1": n_step1,
        "n_step2": n_step2,
        "n_step3": n_step3,
        "n_unknown": n_unknown,
        "time_seconds": run_time,
        "output_file": output_filename if status == "success" else None,
        "status": status,
    }

    return summary, result_data


# ============================================================================
# MAIN EXECUTION
# ============================================================================
def main():
    parser = argparse.ArgumentParser(
        description="BioTransformer Pipeline — Step 1 of the two-step annotation loop.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--batch",
        "-b",
        default=DEFAULT_BATCH_ID,
        help=f"Batch ID to process (default: {DEFAULT_BATCH_ID}). "
        f"E.g. b3_cassavaonly, b3_cocoyamonly",
    )
    parser.add_argument(
        "--bt-dir",
        required=True,
        help="Path to the directory containing the BioTransformer 3.0 jar file.",
    )
    parser.add_argument(
        "--project-dir",
        default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        help="Path to the project root directory (default: parent of scripts/).",
    )
    args = parser.parse_args()

    BATCH_ID = args.batch
    BT_DIR = os.path.expanduser(args.bt_dir)
    JAR_FILE = os.path.join(BT_DIR, JAR_FILENAME)
    PROJECT_DIR = os.path.expanduser(args.project_dir)

    if not os.path.exists(JAR_FILE):
        print(f"ERROR: BioTransformer jar not found at: {JAR_FILE}")
        print(f"Download from https://bitbucket.org/wishartlab/biotransformer3.0jar")
        return

    INPUT_DIR = os.path.join(PROJECT_DIR, "data", "biotransformer")
    OUTPUT_DIR = os.path.join(PROJECT_DIR, "results", "biotransformer", BATCH_ID)
    INDIVIDUAL_DIR = os.path.join(OUTPUT_DIR, "individual_results")
    INPUT_FILE = os.path.join(INPUT_DIR, f"{BATCH_ID}_compounds_for_biotransformer.csv")

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(INDIVIDUAL_DIR, exist_ok=True)

    if not os.path.exists(INPUT_FILE):
        print(f"ERROR: Input file not found: {INPUT_FILE}")
        print(
            "Please run the biotransformer_prep.ipynb notebook first to generate the input file."
        )
        return

    compounds = pd.read_csv(INPUT_FILE)

    print("=" * 80)
    print("BIOTRANSFORMER PIPELINE - PARALLEL 3-STEP VERSION")
    print("=" * 80)
    print(f"CPUs available: {multiprocessing.cpu_count()}")
    print(f"Parallel workers: {MAX_WORKERS}")
    print(f"Total compounds: {len(compounds)}")
    print(f"Transformation types: {', '.join(BT_TYPES)}")
    print(f"  • env = Environmental microbial metabolism (FERMENTATION)")
    print(f"  • hgut = Human gut microbial metabolism")
    print(f"Steps: {NUM_STEPS} (inferring step from precursor relationships)")
    print(f"\nInput file: {INPUT_FILE}")
    print(f"Output directory: {OUTPUT_DIR}")
    print(f"Individual results: {INDIVIDUAL_DIR}")

    # Prepare tasks - ONE task per compound/bt_type
    # Convert rows to dicts to avoid pickle issues with pandas Series
    tasks = []
    for idx, row in compounds.iterrows():
        row_dict = row.to_dict()
        for bt_type in BT_TYPES:
            tasks.append((row_dict, bt_type, INDIVIDUAL_DIR, BT_DIR, JAR_FILE))

    total_tasks = len(tasks)
    print(f"Total runs: {len(compounds)} × {len(BT_TYPES)} = {total_tasks}")
    print("=" * 80)

    # Run in parallel
    all_predictions = []
    run_summary = []
    pipeline_start = time.time()
    completed = 0

    with concurrent.futures.ProcessPoolExecutor(max_workers=MAX_WORKERS) as executor:
        future_to_task = {
            executor.submit(process_single_task, task): task for task in tasks
        }

        print("\nProcessing in parallel...")

        for future in concurrent.futures.as_completed(future_to_task):
            completed += 1
            try:
                summary, df = future.result()
                run_summary.append(summary)

                if df is not None:
                    all_predictions.append(df)
                    symbol = "✓"
                else:
                    symbol = "○" if summary["status"] == "no_metabolites" else "✗"

                pct = (completed / total_tasks) * 100
                print(
                    f"\r[{completed}/{total_tasks} | {pct:.1f}%] {symbol} "
                    f"Feature {summary['feature']} {summary['bt_type']}: "
                    f"{summary['n_metabolites']} total "
                    f"(s1:{summary['n_step1']} s2:{summary['n_step2']} s3:{summary['n_step3']}) "
                    f"| {summary['time_seconds']:.1f}s",
                    end="",
                    flush=True,
                )

            except Exception as exc:
                print(f"\nTask generated an exception: {exc}")

    print("\n\n" + "=" * 80)
    print("COMBINING ALL RESULTS")
    print("=" * 80)

    # Combine Results
    combined_file = None
    if len(all_predictions) > 0:
        combined_df = pd.concat(all_predictions, ignore_index=True)
        combined_file = os.path.join(
            OUTPUT_DIR, f"biotransformer_{NUM_STEPS}step_predictions.csv"
        )
        combined_df.to_csv(combined_file, index=False)

        print(f"\n✓ Combined predictions saved:")
        print(f"  File: {combined_file}")
        print(f"  Total predicted metabolites: {len(combined_df):,}")
        print(f"  Unique origin features: {combined_df['origin_feature'].nunique()}")
        print(f"  Columns: {len(combined_df.columns)}")

        # Print breakdown by transformation step
        print(f"\n📊 Breakdown by transformation step:")
        for step in sorted(combined_df["transformation_step"].unique()):
            count = len(combined_df[combined_df["transformation_step"] == step])
            pct = (count / len(combined_df)) * 100
            if step == 0:
                print(f"  • Unknown:  {count:>6,} ({pct:>5.1f}%)")
            else:
                print(f"  • Step {step}:   {count:>6,} ({pct:>5.1f}%)")

        # Breakdown by bt_type
        print(f"\n📊 Breakdown by transformation type:")
        for bt_type in BT_TYPES:
            type_count = len(combined_df[combined_df["bt_type"] == bt_type])
            pct = (type_count / len(combined_df)) * 100
            print(f"  • {bt_type}: {type_count:>6,} ({pct:>5.1f}%)")

        # Summary by SMILES source
        print(f"\n📊 Breakdown by SMILES source:")
        for source in combined_df["smiles_source"].unique():
            source_count = len(combined_df[combined_df["smiles_source"] == source])
            pct = (source_count / len(combined_df)) * 100
            print(f"  • {source}: {source_count:>6,} ({pct:>5.1f}%)")

        # Most common reactions
        if "Reaction" in combined_df.columns:
            print(f"\n📊 Top 10 most common reactions:")
            reaction_counts = combined_df["Reaction"].value_counts().head(10)
            for reaction, count in reaction_counts.items():
                print(f"  • {reaction[:60]}: {count}")
    else:
        print("\n✗ No metabolites predicted from any compound")

    # Save Summary
    summary_df = pd.DataFrame(run_summary)
    summary_file = os.path.join(
        OUTPUT_DIR, f"biotransformer_{NUM_STEPS}step_summary.csv"
    )
    summary_df.to_csv(summary_file, index=False)

    print(f"\n✓ Run summary saved:")
    print(f"  File: {summary_file}")
    print(f"  Total runs: {len(summary_df)}")
    print(f"  Successful predictions: {(summary_df['n_metabolites'] > 0).sum()}")

    total_time = time.time() - pipeline_start

    print(f"\n" + "=" * 80)
    print("PIPELINE COMPLETE - FINAL SUMMARY")
    print("=" * 80)
    print(f"Total time: {total_time:.1f}s ({total_time/60:.1f} minutes)")
    if len(compounds) > 0:
        avg_time = total_time / len(compounds)
        print(f"Average per compound: {avg_time:.1f}s")

    print(f"\n📊 Results:")
    print(f"  • Total compounds processed: {len(compounds)}")
    print(f"  • Total runs: {len(summary_df)}")
    print(f"  • Successful predictions: {(summary_df['n_metabolites'] > 0).sum()}")
    print(f"  • Total metabolites: {summary_df['n_metabolites'].sum():,}")

    if len(all_predictions) > 0:
        print(f"\n📊 By transformation type:")
        for bt_type in BT_TYPES:
            type_data = summary_df[summary_df["bt_type"] == bt_type]
            total_metabolites = type_data["n_metabolites"].sum()
            features_with_results = (type_data["n_metabolites"] > 0).sum()
            print(
                f"  • {bt_type:12s}: {total_metabolites:4d} metabolites from {features_with_results}/{len(compounds)} features"
            )

        print(f"\n📊 By SMILES source:")
        for source in summary_df["smiles_source"].unique():
            source_data = summary_df[summary_df["smiles_source"] == source]
            if len(source_data) > 0:
                total_metabolites = source_data["n_metabolites"].sum()
                features_with_results = (source_data["n_metabolites"] > 0).sum()
                print(
                    f"  • {source:12s}: {total_metabolites:4d} metabolites from {features_with_results} compounds"
                )

    print(f"\n📁 Output files:")
    print(
        f"  • Combined predictions: {combined_file if len(all_predictions) > 0 else 'N/A'}"
    )
    print(f"  • Run summary: {summary_file}")
    print(
        f"  • Individual results: {INDIVIDUAL_DIR}/ ({len([f for f in os.listdir(INDIVIDUAL_DIR) if f.endswith('.csv')])} files)"
    )

    print("=" * 80)
    print("✓ Pipeline complete! Ready for matching to unannotated features.")
    print("=" * 80)


if __name__ == "__main__":
    main()
